# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synbytapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='s_image',
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='slidertext',
            name='model_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synbytapp.SliderImage', verbose_name='Slider Image'),
        ),
    ]
