# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synbytapp', '0002_auto_20180321_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='300', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='1500', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='s_image',
            field=models.ImageField(blank=True, help_text='Slider Image', null=True, upload_to='products', verbose_name='Slider Image'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
