# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synbytapp', '0003_auto_20180321_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='s_image',
        ),
    ]
