# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synbytapp', '0004_remove_sliderimage_s_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidertext',
            name='model_a',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='s_image',
            field=models.ImageField(blank=True, help_text='Slider Image', null=True, upload_to='images/', verbose_name='Slider Image'),
        ),
        migrations.DeleteModel(
            name='SliderText',
        ),
    ]
