# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synbytapp', '0009_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='300', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='300', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='p_image',
            field=models.ImageField(blank=True, help_text='Portfolio Image', null=True, upload_to='products'),
        ),
    ]
