# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synbytapp', '0012_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='About Us Title', max_length=200)),
                ('description', models.CharField(blank=True, help_text='About Us', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Support Title', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Support', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Support Title', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Support', max_length=2000, null=True)),
            ],
        ),
    ]
