# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synbytapp', '0013_aboutus_support_termsofuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(blank=True, help_text='About Us', max_length=2000, null=True),
        ),
    ]
